"""add_category_to_template

Revision ID: d215f44db5b4
Revises: b9e7e81188fe
Create Date: 2025-12-06 06:03:22.960014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd215f44db5b4'
down_revision: Union[str, Sequence[str], None] = 'b9e7e81188fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'category')
    # ### end Alembic commands ###
